version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: Australia/Sydney
    open-pull-requests-limit: 3
    reviewers:
      - r-k-b
